name: Build Android APK

on:
  push:
    branches: [ "main" ] # O la rama que uses, ej: "master" o "develop"
  workflow_dispatch: # Permite ejecutarlo manualmente desde la web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version: '3.19.0' # Descomenta si necesitas una versión fija

      - name: Get Dependencies
        run: flutter pub get

      # --- Secrets Github Actions: ---
      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
      # ----------------------------
      - name: Build APK (Debug)
        # Usamos --debug para evitar configurar firmas digitales complejas por ahora
        run: flutter build apk --debug --split-per-abi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk
          # Nota: flutter genera varios APKs, subimos el más común o usa 'app-debug.apk' si es universal